// get first 20 fibnum using loop
function getFibNum(n){
    console.log("This is generated by loop using loop.")
    let firstNum = 0;
    let secondNum = 1;
    let nextNum
    console.log(firstNum)
    console.log(secondNum)
    for (let i = 2; i <= n; i++){
        nextNum = firstNum + secondNum;
        firstNum = secondNum;
        secondNum = nextNum
        console.log(nextNum)
    }
}
getFibNum(20)

// get fib num using recursion func

function getFib(n){
    if (n <= 1){
        return n;
    }

    return getFib(n - 1) + getFib(n - 2)
}

function getnxtfibprinted(c){
    console.log("Using recursive function.")
    for (let i = 0; i <= c; i++){
        console.log(getFib(i))
        console.log("hello")
    }
}
getnxtfibprinted(20)